### PR TITLE
Issue #25: Add check that memcached is actually running, before integ…

### LINKED ISSUE #25: Integration tests fail when no memcached is running
We should add a check, that the memcached is actually running

### PR DESCRIPTION
**Pull request by Schrank**
Fixes #25

### CODE REVIEW

File: tests/Integration/Suites/MemcachedKeyValueStoreTest.php [hunk 1]
```diff
@@ -1,6 +1,6 @@
 <?php
 
-declare(strict_types=1);
+declare(strict_types = 1);
```
Comment (tim-bezhashvyly) [inline tests/Integration/Suites/MemcachedKeyValueStoreTest.php]: Why?

File: tests/Integration/Suites/MemcachedKeyValueStoreTest.php [hunk 2]
```diff
@@ -22,6 +22,9 @@ protected function setUp()
     {
         $client = new \Memcached();
         $client->addServer(self::MEMCACHED_HOST, self::MEMCACHED_PORT);
+        if (!isset($client->getStats()[self::MEMCACHED_HOST . ':' . self::MEMCACHED_PORT])) {
+            self::markTestSkipped('You need a running memcached to run the integration tests!');
+        }
```
Comment (tim-bezhashvyly) [inline tests/Integration/Suites/MemcachedKeyValueStoreTest.php]: Please add new line before and after this block.

File: tests/Integration/Suites/MemcachedKeyValueStoreTest.php [hunk 3]
```diff
@@ -22,6 +22,9 @@ protected function setUp()
     {
         $client = new \Memcached();
         $client->addServer(self::MEMCACHED_HOST, self::MEMCACHED_PORT);
+        if (!isset($client->getStats()[self::MEMCACHED_HOST . ':' . self::MEMCACHED_PORT])) {
+            self::markTestSkipped('You need a running memcached to run the integration tests!');
```
Comment (tim-bezhashvyly) [inline tests/Integration/Suites/MemcachedKeyValueStoreTest.php]: Please use `$this->` as this is not a static method.

File: tests/Integration/Suites/MemcachedKeyValueStoreTest.php [hunk 4]
```diff
@@ -22,6 +22,9 @@ protected function setUp()
     {
         $client = new \Memcached();
         $client->addServer(self::MEMCACHED_HOST, self::MEMCACHED_PORT);
+        if (!isset($client->getStats()[self::MEMCACHED_HOST . ':' . self::MEMCACHED_PORT])) {
```
Comment (tim-bezhashvyly) [inline tests/Integration/Suites/MemcachedKeyValueStoreTest.php]: Please extract `isset($client->getStats()[self::MEMCACHED_HOST . ':' . self::MEMCACHED_PORT])` into a method (e.g. `memcachedIsRunning`).

File: tests/Integration/Suites/MemcachedKeyValueStoreTest.php (hunk 1 above)
Comment (Schrank) [inline tests/Integration/Suites/MemcachedKeyValueStoreTest.php]: Auto format, It thought about reseting it, but we are doing before and after every = spaces, therefore I think it is only hazzle. I can't configure this special exception in PHPStorm.

File: tests/Integration/Suites/MemcachedKeyValueStoreTest.php (hunk 3 above)
Comment (Schrank) [inline tests/Integration/Suites/MemcachedKeyValueStoreTest.php]: Unfortunately it is.

\PHPUnit_Framework_Assert::markTestSkipped
public static function markTestSkipped($message = '')

File: tests/Integration/Suites/MemcachedKeyValueStoreTest.php (hunk 1 above)
Comment (tim-bezhashvyly) [inline tests/Integration/Suites/MemcachedKeyValueStoreTest.php]: Then we will have to reformat it for all files in all repositories.

File: tests/Integration/Suites/MemcachedKeyValueStoreTest.php (hunk 3 above)
Comment (Schrank) [inline tests/Integration/Suites/MemcachedKeyValueStoreTest.php]: as all assert methods are...
    public static function assertArrayHasKey($key, $array, $message = '')


But I can change it

Comment (tim-bezhashvyly) [inline tests/Integration/Suites/MemcachedKeyValueStoreTest.php]: Heave you tired calling it as `$this->markTestSkipped()`. I mean the `setUp` method it not static.

File: tests/Integration/Suites/MemcachedKeyValueStoreTest.php (hunk 1 above)
Comment (tim-bezhashvyly) [inline tests/Integration/Suites/MemcachedKeyValueStoreTest.php]: Then let's for now remove spaces here.

File: tests/Integration/Suites/MemcachedKeyValueStoreTest.php [hunk 5]
```diff
@@ -23,8 +23,9 @@ protected function setUp()
         $client = new \Memcached();
         $client->addServer(self::MEMCACHED_HOST, self::MEMCACHED_PORT);
         $client->deleteMulti(['foo', 'key1', 'key2']);
-
         $this->keyValueStore = new MemcachedKeyValueStore($client);
+
+        $this->skipIfMemcacheIsNotRunning($client);
```
Comment (tim-bezhashvyly) [inline tests/Integration/Suites/MemcachedKeyValueStoreTest.php]: Why you moved it to the bottom? Woun't is be a problem calling `deleteMulti` if memcached is not running?

File: tests/Integration/Suites/MemcachedKeyValueStoreTest.php [hunk 6]
```diff
@@ -57,4 +58,16 @@ public function testExceptionIsThrownIfValueIsNotSet()
         $this->expectException(KeyNotFoundException::class);
         $this->assertFalse($this->keyValueStore->get('foo'));
     }
+
+    /**
+     * @param \Memcached $client
+     */
```
Comment (tim-bezhashvyly) [inline tests/Integration/Suites/MemcachedKeyValueStoreTest.php]: Please addd parameter type to method signature and remove PHPDoc.

To tell the truth I was thinking of extracting only `isset` into a method but what you did is also okay. Not that obvious while reading but still okay.

File: tests/Integration/Suites/MemcachedKeyValueStoreTest.php (hunk 5 above)
Comment (Schrank) [inline tests/Integration/Suites/MemcachedKeyValueStoreTest.php]: It will be called nontheless, as long as we don't throw an exception. There is no way to stop a test in setUp imho, so it doesn't matter where we tell phpunit to ignore whatever it just found - if you know a way to not run the test, please tell me, then I'll change it

Comment (Schrank) [inline tests/Integration/Suites/MemcachedKeyValueStoreTest.php]: all fine. Just learned that (of course) markSkipped is an exception...
